### ISSUE TITLE
Milestone IV tasks

### ISSUE THREAD

**Issue by CSJong06** [CSJong06/Youtuber-Viewer#11]
- [x] create a settings panel

- [x] move items into settings panel 

- [x] create user form

- [x] store user information
