### ISSUE TITLE
Milestone I tasks

### ISSUE THREAD

**Issue by CSJong06** [CSJong06/Youtuber-Viewer#4]
- [x] Use HTML5 elements in my index.html 
- [x] Embedded a YouTube Video in my index.html
- [x] Styled my CSS page and displayed my Video on my page that allows users to view and navigate the site easily
- [x] Displayed the video attributes (title, description, watch time etc.) 
- [x] Submitted my GitHub Link to Beacon
- [x] Added the latest code to GitHub
