### ISSUE TITLE
Milestone II tasks

### ISSUE THREAD

**Issue by CSJong06** [CSJong06/Youtuber-Viewer#8]
- [x] add more videos
- [x] add a menu to switch between video
- [x] make the menu work
- [x] style
